name: Deploy ZCOR Server Application

on:
  push:
      branches:
          - production

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t zcor/zcor-server .
            - name: Publish Image to docker hub
              run: docker push zcor/zcor-server:latest
    deploy:
        needs: build
        runs-on:  self-hosted
        steps:
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull image from docker hub
              run: docker pull zcor/zcor-server:latest
            - name: Delete old container
              run: docker rm -f zcor-server-container
            - name: Run Docker Container
              run: >
                docker run -d -p 5000:5000 --name zcor-server-container
                -e MONGO_URL='${{ secrets.MONGO_URL }}'
                -e JWT_SECRET='${{ secrets.JWT_SECRET }}'
                -e JWT_EXPIRES_IN='${{ secrets.JWT_EXPIRES_IN }}'
                -e NODE_ENV='production'
                -e COOKIE_NAME='${{ secrets.COOKIE_NAME }}'
                -e SMTP_HOST='${{ secrets.SMTP_HOST }}'
                -e SMTP_PORT='${{ secrets.SMTP_PORT }}'
                -e SMTP_USER='${{ secrets.SMTP_USER }}'
                -e SMTP_PASS='${{ secrets.SMTP_PASS }}'
                -e SMTP_FROM='${{ secrets.SMTP_FROM }}'
                -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}'
                zcor/zcor-server
            - name: Delete old image
              run: docker system prune -f
